### ISSUE TITLE
[doc] WebDAV on Windows

### ISSUE THREAD

**Issue by Ekleog** [nextcloud/documentation#1001]
Hello,

Just wanted to point out that https://github.com/owncloud/documentation/pull/2668#issuecomment-260697742 should likely be added to Nextcloud's docs. Didn't manage to run the integrated WebDAV client until following this procedure.

HTH,
Leo

**Comment by fgsl** [comment]
I think that this issue was solved by this [commit](https://github.com/nextcloud/documentation/commit/2f9c384209013cb97974737ea434e947bd50c26d)

**Comment by Ekleog** [comment]
I don't think it's solved. The problem here is that one needs to configure windows to automatically start the webdav client and reboot before being able to add a webdav device, as far as I understand. Not in the URL of the webdav endpoint. Also, my nextcloud version appears to already include this commit as the linked url is `/webdav`.

**Comment by novalis111** [comment]
I can confirm that this is not solved and should be documented. Tested with Nextcloud 15 and nginx 1.14.0 on Ubuntu Server. The problem is Windows handling of WebDAV connections falling back to root. The nginx config needs to be tweaked to work around this, and the windows file limit for WebClient needs to be raised.

https://github.com/owncloud/documentation/pull/2668#issuecomment-259909754

https://support.microsoft.com/en-us/help/900900/folder-copy-error-message-when-downloading-a-file-that-is-larger-than#letmefixitmyselfalways

**Comment by tflidd** [comment]
Good point, when checking things on the webdav end point, I had to start the service as well: https://github.com/nextcloud/documentation/pull/1505#pullrequestreview-948613096
